### ISSUE TITLE
ERROR when creating a Dedicated Server :((((

### ISSUE THREAD

**Issue by bryan411001** [lolleko/guesswho#56]
I get this error on the thread when I start the .bat file

[ERROR] gamemodes/guess_who/gamemode/cl_lang.lua:8: attempt to index a nil value
  1. translate - gamemodes/guess_who/gamemode/cl_lang.lua:8
   2. RoundStateChange - gamemodes/guess_who/gamemode/cl_round.lua:16
    3. func - gamemodes/guess_who/gamemode/cl_round.lua:46
     4. unknown - lua/includes/extensions/net.lua:32

I am able to join the game, but I have a white screen. I can still hear the game noise in the background though. I can also hit tab and the scoreboard pops up. Please help

**Comment by EdoTM** [comment]
**Did you modify some translations?**
In that case, try to use a different language or to reset the language file. If you did not, please skip this point.

**Are you sure you are using the latest version of Guess Who?**
The "guess_who" folder doesn't exist anymore. Now there is a "guesswho" folder (without underscore). If you are *not* using the latest version of guess who (**2.1g** at the moment), update the addon. If you have modified the name of the folder to "guess_who", instead of "guesswho", change it back.

**Comment by lolleko** [comment]
This error is cause by an invalid sh_config.lua file don't use sh_config.lua anymore use the built in Gui in the F1 menu for customisation!
