### ISSUE TITLE
Error lua clientside

### ISSUE THREAD

**Issue by TheCocasio** [lolleko/guesswho#58]
```
[ERROR] lua/weapons/weapon_gw_disguise.lua:8: bad argument #1 to 'SetModel' (string expected, got nil)
  1. SetModel - [C]:-1
   2. Ability - lua/weapons/weapon_gw_disguise.lua:8
    3. unknown - lua/weapons/weapon_gwbase.lua:72
```

```
[ERROR] lua/weapons/weapon_gw_shockwave.lua:21: attempt to call method 'ApplyStun' (a nil value)
  1. Ability - lua/weapons/weapon_gw_shockwave.lua:21
   2. unknown - lua/weapons/weapon_gwbase.lua:72
```

**Comment by lolleko** [comment]
Which version are you using because there is no:

SetModel on line 8 https://github.com/lolleko/guesswho/blob/master/gamemodes/guesswho/entities/weapons/weapon_gw_disguise.lua#L8

and not apply stun on line 21
https://github.com/lolleko/guesswho/blob/master/gamemodes/guesswho/entities/weapons/weapon_gw_shockwave.lua#L21

**Comment by TheCocasio** [comment]
Its version of workshop.
